logging.charset.console=UTF-8
spring.application.name=notification-service
#Eureka Connection
eureka.client.service-url.defaultZone=${EUREKA_URL:http://eureka:eureka123@localhost:8761/eureka/}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP:true}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:notification-service}
#Connectuin to Config Service
spring.config.import=optional:configserver:
spring.cloud.config.discovery.enabled=${CONFIG_DISCOVERY_ENABLED:true}
spring.cloud.config.discovery.service-id=${CONFIG_SERVICE_ID:config-service}
#Connection Resource
spring.cloud.config.username=${CONFIG_USERNAME:config}
spring.cloud.config.password=${CONFIG_PASSWORD:config123}
spring.cloud.config.fail-fast=${CONFIG_FAIL_FAST:true}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
#Kafka for bus
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID:notification-service-group}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
